name: my_app_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#앱 버전
version: 1.0.0+1
# 다트 버전
environment:
  sdk: '>=2.19.3 <3.0.0'

#종속성, 의존성, 라이브러리
dependencies:
  flutter:
    sdk: flutter
# ex) A라는 라이브러리를 가져왔을 때 A라이브러리가 B,C라이브러리를 사용
  #B는 D를 C는 E라는 라이브러리 사용
  #종속성을 이용하면, 라이브러리가 필요로하는 모든 하위 라이ㅡ러리를 알아서 다운로드하고 관리해줌


  cupertino_icons: ^1.0.2
  #버전 앞에 아무것도 없으면 - 버전 고정
  #버전 앞에 " ^ "있으면 - 호환 가능한 최신 버전을 가져옴
  #버전 앞에 " ~ "있으면 = 버그가 수정된 최신버전
  #앱 개발 시 ^ 사용
  #앱 개봘 완료 시 기호 없앰
  # 앱 유지보수 시 ^ 또는 ~ 또는 최신 버전 업데이트
  # lock 파일은 건들지 않는다. git 에 공유한다
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
